development:
  adapter: async

test:
  adapter: async

production:
  # Heroku対応により、以下３行コメントアウト
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: naituusya_production
  adapter: async
